version: '3'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: always
  elasticsearch:
    image: 'bklite/elasticsearch'
    ports:
      - '9200:9200'
    restart: always
    environment:
       discovery.type: "single-node"
       xpack.security.enabled: "true"
       ELASTIC_PASSWORD: "password"
       TZ: "UTC"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
volumes:
  postgres:
  elasticsearch: