version: '3.5'

services:
  rabbitmq:
    restart: always
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672    
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
  redis:
    image: redis:5
    restart: always
    ports:
      - 6379:6379
    networks:
      - bk-lite
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes  --requirepass password

  minio:
    image: 'minio/minio'
    ports:
      - '9000:9000'
      - '9001:9001'   
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio-bklite
    command: server --console-address :9001 /data
    networks:
      - bk-lite    
    volumes:
      - minio-data:/data
  nats:
    image: nats:2.10.25
    restart: always
    ports:
      - 4222:4222
    networks:
      - bk-lite
    volumes:
      - nats-data:/nats
      - ${PWD}/conf/nats.conf:/etc/nats/nats.conf
    command: -c /etc/nats/nats.conf

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - bk-lite
    ports:
      - "5432:5432"
    restart: always
  
volumes:
  postgres:
  nats-data:
  minio-data:
  redis-data:

networks:
  bk-lite:
    external: true
